### ISSUE TITLE
下载llama-2需要验证凭证

### ISSUE THREAD

**Issue by Garand0o0** [LetheSec/HuggingFace-Download-Accelerator#10]
下载llama-2需要验证凭证，我已经获得了通过了meta的申请和huggingface的认证。
![微信截图_20231229122142](https://github.com/LetheSec/HuggingFace-Download-Accelerator/assets/38201671/449bc8fa-c466-4069-bd28-3b8c1d8e887f)

直接用命令下载时`python hf_download.py --model meta-llama/Llama-2-7b-chat-hf --save_dir ./hf_hub`，提示需要凭证，hf_download.py怎么添加凭证。

**Comment by LetheSec** [comment]
使用 --token 参数，参考 https://github.com/LetheSec/HuggingFace-Download-Accelerator/issues/4

**Comment by Garand0o0** [comment]
> 使用 --token 参数，参考 #4

谢谢
