### ISSUE TITLE
THUDM/ChatGLM-6B下载失败

### ISSUE THREAD

**Issue by gxlover0625** [LetheSec/HuggingFace-Download-Accelerator#15]
![image](https://github.com/LetheSec/HuggingFace-Download-Accelerator/assets/87931729/d3a9fcf8-babd-4655-9f40-e2fbf8a02335)
执行代码python hf_download.py --model THUDM/chatglm3-6b，程序未报错，但进度条不动，不知道是什么原因？欢迎您的解答！

**Comment by LetheSec** [comment]
如果经过长时间等待还是无法下载成功的话，可以尝试一下这个办法重新下载： https://github.com/LetheSec/HuggingFace-Download-Accelerator/issues/9#issuecomment-1916403775

**Comment by gxlover0625** [comment]
谢谢你的建议，我后面采用清华大学云盘下载模型和权重了，不知道是不是实验室的服务器不允许访问外网的问题。
