### ISSUE TITLE
huggingface-cli: error问题

### ISSUE THREAD

**Issue by zwkkk** [LetheSec/HuggingFace-Download-Accelerator#2]
export HF_HUB_ENABLE_HF_TRANSFER= 1
export HF_ENDPOINT= https://hf-mirror.com
usage: huggingface-cli <command> [<args>]
huggingface-cli: error: argument {env,login,whoami,logout,repo,lfs-enable-largefiles,lfs-multipart-upload,scan-cache,delete-cache}: invalid choice: 'download' (choose from 'env', 'login', 'whoami', 'logout', 'repo', 'lfs-enable-largefiles', 'lfs-multipart-upload', 'scan-cache', 'delete-cache')

**Comment by LetheSec** [comment]
试一试重新手动安装一下：

```
pip install -U huggingface_hub
```

**Comment by SpursGoZmy** [comment]
> 试一试重新手动安装一下：
> 
> ```
> pip install -U huggingface_hub
> ```

遇到了同样的问题，用这个解决了！速度真滴快！！

**Comment by Modas-Li** [comment]
未解决

**Comment by yema2020** [comment]
未解决

**Comment by chaofengc** [comment]
python 3.12似乎有问题，可以尝试降级python版本

**Comment by chaofengc** [comment]
尝试不同的python版本重新安装或许可以解决，尚不清楚原因

**Comment by deapge** [comment]
python 版本需要大于 3.7

**Comment by shiwxyz** [comment]
> python 版本需要大于 3.7

执行上面的命令不行，你升级解决了吗？

**Comment by buptlj** [comment]
pip install huggingface_hub==0.17.0

**Comment by lrybbbccc** [comment]
我也经常遇到这个问题。可正常运行的版本：
python==3.10.14
huggingface-hub==0.24.6

**Comment by InTheFuture7** [comment]
感谢，应该就是 python 和 hugggingface-hub 的版本兼容性问题了。

实测：python=3.10.16，huggingface-hub==0.24.6或0.35都可以
