### ISSUE TITLE
建议添加参数，忽略下载某些文件

### ISSUE THREAD

**Issue by myaijarvis** [LetheSec/HuggingFace-Download-Accelerator#3]
这个默认下载所有框架的模型文件，比如tf、torch等等。
能否添加一些参数，忽略下载某些文件，（比如忽略*.h5，*.msgpack等等）

**Comment by LetheSec** [comment]
现在可以通过 `--include` 和 `--exlucde`参数，指定下载或忽略某些文件。

**Comment by LetheSec** [comment]
Problem solved
