### ISSUE TITLE
大文件总是请求失败 Exception: Failed too many failures in parall

### ISSUE THREAD

**Issue by BlackBearBiscuit** [LetheSec/HuggingFace-Download-Accelerator#6]
model-00001-of-00006.safetensors:  31%|██▋      | 1.48G/4.84G [07:22<16:46, 3.34MB/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 515, in http_get
    hf_transfer.download(
Exception: Failed too many failures in parallel (3): PyErr { type: <class 'Exception'>, value: Exception('Error while downloading: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody }) }'), traceback: None } (NoPermits)

**Comment by LetheSec** [comment]
是运行之后手动中断了下载，然后重复运行了多次吗？

**Comment by BlackBearBiscuit** [comment]
没有啊，就是运行了一次之后然后遇到大文件就会出现这个

**Comment by LetheSec** [comment]
额.. 不太清楚你这个是什么原因，暂时没遇到过... 

实在不行，可以试试到 https://hf-mirror.com/ 上面手动下载

**Comment by MachineT-T** [comment]
> 是运行之后手动中断了下载，然后重复运行了多次吗？

手动中断下载后，后面重复运行好像会报错，要怎么解决

**Comment by wang-quanshen** [comment]
请问有解决方案了吗？我也遇到了这种情况Exception: Failed too many failures in parallel (3): Request: error sending request for url ([https://cdn-lfs-us-1.hf.co/repos/64/73/64732f43e0e34948b4](https
